name: Benchmarks

on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        configuration: [ Release ]
  
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet '3.1.x'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup dotnet '5.x'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - name: Install dependencies
        run: dotnet restore
      - name: Install Benchmark dotnet tool
        run: dotnet tool install -g BenchmarkDotNet.Tool
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Benchmark
        run: dotnet benchmark Benchmarks.dll --filter *
